package truequep.domain.enumeration;

/**
 * The TipoObjeto enumeration.
 */
public enum TipoObjeto {
    ALIMENTACIONBEBIDAS, ARTEANTIGUEDADES, VEHICULOS, CASAHOGAR, COLECCION, DEPORTES, EDUCACION, IMAGENSONIDO, INFORMATICAELECTRONICA, INMOBILIARIA, JOYERIA, JUEGOSJUGUETES, LIBROSREVISTASCOMICS, MUSICA, ROPACALZADO, SALUDBELLEZA, SERVICIOS, MANOOBRA, TELEFONIA, TIEMPOLIBRE
}
